name: Tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/install-leiningen
    - name: Install dependencies
      run: |
        lein with-profile shadow deps
        npm install
    - name: Run ClojureScript tests 
      run: |
        lein build-test
        npx karma start --single-run
